name: Daily BeautyDrop Fetch

on:
  schedule:
    - cron: "0 3 * * *"  # Her gece 03:00 UTC
  workflow_dispatch:     # Elle tetikleme

concurrency:
  group: daily-scrape
  cancel-in-progress: false
  
permissions:
  contents: write
 
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
              with:
with:with:
          fetch-depth: 0
          persist-credentials: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        # Use `npm install` instead of `npm ci` to avoid requiring a lock file.  The
        # repository does not currently include a package‑lock.json, and `npm ci`
        # fails without it.  `npm install` will install dependencies based on
        # package.json directly.
        run: npm install

      - name: Install Playwright (with system deps)
        run: npx playwright install --with-deps

      - name: Run bot
        run: node bot.mjs --headless --maxPerPage=60

       - name: Commit files
      run: |
        git config user.name  "beautydrop-bot"
        git config user.email "bot@users.noreply.github.com"
        git add data/deals-*.json || true
        git commit -m "auto: daily update ${{ github.run_id }}" || echo "No changes"

    - name: Pull latest main (rebase to avoid non-FF)
      run: |
        git fetch origin main
          git pull --rebase origin main || true

    - name: Push changes
      run: |
        git push origin HEAD:main
